version: "3"

services:
  app:
    build: .
    container_name: django-gunicorn
    restart: always
    ports:
      - "8000:8000"
    command:
      bash -c "python3 /src/manage.py collectstatic --noinput && gunicorn --chdir src --bind :8000 city_weather.wsgi:application"
    env_file:
      - /etc/.env



  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app



